### ISSUE TITLE
Enable configs for omniauth providers at the org level

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#10]
## Info
- **where to code?** [meta decidim proposal](https://meta.decidim.org/processes/roadmap/f/122/proposals/14875) is in status evaluating, meaning this can be coded directly on decidim/decidim master branch and a PR can be made
- **deadline** : ideally end of november or first week of December

## Specs
This feature aims to enhance the capabilities of the multi-tenant mode of Decidim.

Currently when using multi-tenant, the omniauth config you have for social providers (or other SSO) are made for the whole installation and are shared by all orgs.

Problem is organizations have different hosts and you can only declare one call back with the social providers.

As a super admin (meaning I have access to /system) I want to be able to manage my omniauth configuration where I create and edit the organizations.

For each orgs should be available :
- All the providers (activated on the installation) and the necessary fieds to set them up ( clients id and client secret)
- As all the orgs on the same install won't want to activate all the omniauth connectors I'll need a checkbox to activate them one by one so that they display on the sign in and sign up page (and the modals). Alternatively if config fields are not filled the app could understand that it shouldn't activate them.

### Task breakdown
- [ ] Add a new form to introduce key/secrets/url for oauth providers through a dynamic form in /system
	- twitter, facebook, google, other Decidims but also custom omniauth setups that might be present on the install, SSO, e-ID protocols that can work with SAML, LDAP etC.. Only for those configured in secrets.yml (as enabled: yes). The system will fallback to the data of secrets.yml if valid data is provided.
- [ ] Add a checkbox to enable/disable the specific provider at multitenant level.
- [ ] Refactor logic to let the system behave accordingly.
- [ ] Tests/PRs to [decidim/decidim](https://github.com/decidim/decidim/)

**Comment by virgile-dev** [comment]
## Mockups 
Here is what the dynamic form would look like (don't mind the /admin styling this would go into /system) :
- [ ] providers are detected automatically
- [ ] a checkbox allow to activate / desactivate the omnitauth provider
![decidim local osp cat_3000_admin_omniauth_settings_edit_locale=fr](https://user-images.githubusercontent.com/11473995/68388806-c06c4d00-0161-11ea-96db-d7c14266e994.png)

Here is the code that generates it : 

```
<%= decidim_form_for(@form, html: { class: "form edit_omniauth_settings" }, url: decidim_omniauth_extras.omniauth_settings_path, method: :put) do |f| %>

  <div class="card">
    <div class="card-divider">
      <h2 class="card-title"><%= t ".title" %></h2>
    </div>
  </div>
  <%= f.fields_for :omniauth_settings do %>
    <% Decidim::User.omniauth_providers.select{ |provider| Rails.application.secrets.dig(:omniauth, provider.to_sym, :enabled) }.each do |provider| %>
      <%= f.fields_for provider.to_sym do %>
        <%= render partial: "provider", locals: { f: f, provider: provider} %>
      <% end %>
    <% end %>
  <% end %>

  <div class="button--double form-general-submit">
    <%= f.submit t(".update") %>
  </div>
<% end %>

<pre>
  <%= @form.omniauth_settings %>
</pre>
```

```
<div class="card">
  <div class="card-divider">
    <%= f.check_box :enabled, label: t(".enabled", provider: normalize_provider_name(provider)) %>
  </div>
  <div class="card-section">
    <% Rails.application.secrets.dig(:omniauth, provider.to_sym).keys.select { |k| k != :enabled }.each do |setting| %>
        <%= f.text_field setting, label: normalize_provider_name(setting) %>
    <% end %>
  </div>
</div>
```

**Comment by virgile-dev** [comment]
## Context
We need this mainly to allow the Belgium Federal State to apply different configs of their e-ID solution to organizations form the same installations.

**Comment by virgile-dev** [comment]
## Code snippets that we have to handle the omniauth integratin without having the parameters in advance

```
# frozen_string_literal: true

require "active_support/concern"

module Decidim
  module OmniauthSettingsJsonbAttributes
    extend ActiveSupport::Concern

    class_methods do
      def omniauth_settings_jsonb_attribute(name, fields, *options)
        jsonb_attribute name, fields, default: {}

        fields.each do |provider|
          provider = provider.to_sym
          jsonb_attribute provider, Rails.application.secrets.dig(:omniauth, provider.to_sym).keys.map do |e|
            [e,
              case e
              when :enabled
                Virtus::Attribute::Boolean
              else
                String
              end
            ]
          end

          define_method provider do
            field = public_send(name) || {}
            field[provider.to_s] || field[provider.to_sym]
          end

          define_method "#{provider}=" do |value|
            field = public_send(name) || {}
            public_send("#{name}=", field.merge(provider => super(value)))
          end
        end
      end
    end
  end
end
```

```
mniauth_settings_jsonb_attribute :omniauth_settings, Decidim::User.omniauth_providers.select {
  |provider| Rails.application.secrets.dig(:omniauth, provider.to_sym, :enabled)
}
```

**Comment by amiedes** [comment]
@virgile-dev I'm gonna take care of this 😄

**Comment by virgile-dev** [comment]
Nice @amiedes if you have any doubt let me know in the comments.

**Comment by amiedes** [comment]
For custom auth providers we need a way to communicate the form which fields are available. I suggest using the same format as now:

```yaml
default: &default
  omniauth:
    facebook:
      enabled: true
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    # google etc.
    some_custom_auth_provider:
      enabled: false
      icon_path:
      custom_field_1:
      custom_field_2:
```

So for that configuration the form will show something like this:

![Captura de pantalla 2019-11-13 a las 17 46 11](https://user-images.githubusercontent.com/9287468/68784849-87d6e280-063d-11ea-873e-17bfbdb4a02b.png)

And the following behavior will be applied:

- A field will be displayed in the form for every key. All are strings except `enabled` which is a boolean.
- Settings defined in DB always take precedence, so:
  - Other Decidims upgrading won't be affected, since the values will be empty and they'll fallback to `secrets.yml`
- In the form all providers will be displayed even if `enabled: false`, otherwise there's no way to override it.
- We support defining auth providers both system-wide (if it's not overriden) and per-tenant (if it's overriden)

@virgile-dev can you validate that this is the expected behavior? Do you want to move this issue to https://github.com/decidim/decidim/issues so we can ping the Decidim core for advice?

cc @ferblape @rxnetwalker

**Comment by moustachu** [comment]
Hello guys. (I'm the Lead Dev @ OpenSourcePolitics)

This behavior seems OK for us. Just one question : 
Does any new field defined in the `secrets.yml` will be taken into account (using something like the sample `OmniauthSettingsJsonbAttributes` class we put in example) or did you plan to have a fixed schema for the custom providers ?

**Comment by amiedes** [comment]
Hi @moustachu! 

> Does any new field defined in the secrets.yml will be taken into account

Yes, the form fields are generated according to what is the the config file, so anything new will appear.

**Comment by virgile-dev** [comment]
@amiedes is this going ok ?

**Comment by amiedes** [comment]
@virgile-dev yes, I've already updated the code in local with tests passing and I'm working on deploying this to one of our staging servers so I can test it configuring real omniauth providers.

If everything goes OK I can give you access to it tomorrow or past-tomorrow so you can check it.

**Comment by virgile-dev** [comment]
Great @amiedes ! Let me know :)

**Comment by amiedes** [comment]
Hi @virgile-dev,

I've had a bit of trouble configuring the virtualhosts and SSL certificates for our test server with several tenants.

This is already working https://decidim-test-a.populate.tools/ https://decidim-test-a.populate.tools/ and I've done tests with real Facebook and Google Oauth and it worked fine.

Nevertheless I still have a few things to check so I'll let you know as soon as I've finished.

**Comment by virgile-dev** [comment]
Hola @amiedes !
Thanks a lot. Can you point me to the branch / pull request you are working on ?

**Comment by virgile-dev** [comment]
@amiedes I'd like to have access to /system and /admin can you seed the instance so I can log with admin@example.org and system@example.org

**Comment by amiedes** [comment]
@virgile-dev we've finished testing this. As I said, I've configured the following sites:

**https://decidim-test-a.populate.tools**

With two oauth providers:

- Google
- Facebook (Test App A)

**https://decidim-test-b.populate.tools**

With one oauth provider:

- Facebook (Test App B)

You can login as system in both sites with system@decidim.dev or as admin with admin@decidim.dev. I'm sending you the passwords via e-mail.

I've created a draft PR in decidim for the moment: https://github.com/decidim/decidim/pull/5516. In [this commit](https://github.com/PopulateTools/decidim-demo/commit/9633ae140e0e04fdd672cab825857132b6bbed1e) you can see how I've configured a Decidim application to use the contents of the PR.

In the tenant settings I've configured a couple of *"fake"* custom omniauth providers, to check that the fields defined in `config/secrets.yml` get reflected here:

![image](https://user-images.githubusercontent.com/9287468/69554017-6a8d0700-0fa1-11ea-93b1-f847553452a7.png)

Please test the setup and let us know,

Thanks

cc @furilo @rxnetwalker @ferblape

**Comment by virgile-dev** [comment]
Nice will be testing on our side this week with @moustachu

**Comment by amiedes** [comment]
@virgile-dev @moustachu how is the review going?

**Comment by virgile-dev** [comment]
hey @amiedes I've been swamped with work. I'm hoping I can give you feedback tonight. From what I've seen so far it seems great !

**Comment by andreslucena** [comment]
@virgile-dev just a friendly reminder to review this when you can... Personally I think it's a really good feature for evolving the multitenant system :D

**Comment by paulinebessoles** [comment]
Hi everyone! I have been testing this (cool) feature and I have a few feedbacks and questions : 
- Facebook login works perfectly! 
- I wasn't able to create a working Twitter login, I don't understand the error (Error 500)
- I tried to create a Google login, and 
     - it worked once (I chose the google account I want to be logged with) until being redirected to the platform and then get an "Invalid credentials" error message
     - the other times I get a 401 error (invalid_client)

It might be a wrong config from my part, so I'd like to have your thoughts about this. 

Thank you!

**Comment by amiedes** [comment]
Hi @paulinebessoles, thanks for the feedback!

I've been taking a look and I've spotted a few things:

- [This error](https://github.com/zquestz/omniauth-google-oauth2/issues/197) was preventing the Google login from working, I've fixed it doing [this](https://github.com/zquestz/omniauth-google-oauth2/issues/197#issuecomment-256041753). After solving this I'm being able to login with Google in [https://decidim-test-a.populate.tools/](https://decidim-test-a.populate.tools/) again.
- Take into account that the Google login I've configured for site A won't work for site B, because the application I've created is only configured for the first site (on purpose, to check one site does not affect the other).
- I'm sending you via email screenshots of my Facebook / Google apps, so you can check against yours.
- I did not configure the Twitter login myself because the process for applying for a developer account was more cumbersome that for Facebook / Google. I've done it now and I'll try it when they confirm my account.

**Comment by paulinebessoles** [comment]
Thanks a lot for the answers and advices! 
I succeeded to create a working Google login for site B :) 

My Twitter account is also waiting for approval, so I can't test either. 

But in general, everything seems really good, congrats!
