### ISSUE TITLE
[EPIC] UX improvements on initiatives

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#5]
# This is an EPIC
**Epic description**
We've been studying the initiatives module of Decidim here are a couple of enhancements that would make more generic and easy to use by a broader set of institutions.

Version of decidim --> Master [Decidim/Decidim](https://github.com/decidim/decidim/), objective is to ship it for 0.19 stable

**Related documentation**
- A couple improvements were made to initiative in the 0.18 version of Decidim.

## Subtasks
- [x] Enable global scope selection and signature threshold
- [ ] Option to deactivate promoting committee
- [ ] Simplify initiative creation wizard when there is only one option available (1 type of initiative, 1 type of signature collection, only global scope signature threshold)

### Enable global scope selection and signature threshold
As an admin when adding an initiative scope I should be able to select "Global scope" as a value in Decidim scopes and input a number of supports required. 
<img width="1131" alt="Capture d’écran 2019-08-02 à 19 37 57" src="https://user-images.githubusercontent.com/11473995/62388255-175bf800-b55d-11e9-89a5-cd7aac070135.png">

### Option to deactivate / activate promoting committee
As an admin when configuring an initiative type I should be able to deactivate the "Promoting committee" feature.
<img width="700" alt="Capture d’écran 2019-08-02 à 19 41 46" src="https://user-images.githubusercontent.com/11473995/62388470-b254d200-b55d-11e9-8878-964146e6ff47.png">

When the promoting committee is disabled : 
- [ ] the invite link is not generated
- [ ] the related steps in the creation wizard don't display
<img width="492" alt="Capture d’écran 2019-08-02 à 19 47 02" src="https://user-images.githubusercontent.com/11473995/62388803-8f76ed80-b55e-11e9-81c5-9413bc66598d.png">
- [ ] the committee members tab in admin doesn't display
<img width="701" alt="Capture d’écran 2019-08-02 à 19 43 50" src="https://user-images.githubusercontent.com/11473995/62388754-6eae9800-b55e-11e9-84e4-94f392d064f1.png">

### Simplify initiative creation wizard when there is only one option available
As a user when : 
- [ ] only "Global scopes" is available
- [ ] only 1 type of signature collection is available

Then the application should prefill those field with the unique option and not display them in the "create" step of the initiative wizard.
<img width="506" alt="Capture d’écran 2019-08-02 à 19 51 07" src="https://user-images.githubusercontent.com/11473995/62389120-365b8980-b55f-11e9-8ed1-e2b84b06daf9.png">

**Comment by oriolgual** [comment]
@virgile-dev are these changes to be made at your fork or directly at decidim? If the latter, are they approved by the product team?

**Comment by virgile-dev** [comment]
@oriolgual We'll be using Decidim's master for this project. We'd like it to go directly on Decidim's master. I had a call with Arnau, most changes should be ok.

Meta Decidim proposal --> https://meta.decidim.org/processes/roadmap/f/122/proposals/14722
